features:
  funda_lag_days: 10          # anti-leakage: ffill fundamental setelah announce_date + 10 hari
  rsi_period: 14
  atr_period: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  stoch_k: 14
  stoch_d: 3
  vol_z_window: 60

labeling:
  horizon_n: 5                # vertical barrier N hari
  tp_mult: 1.5                # multiplier utk TP
  sl_mult: 1.0                # multiplier utk SL
  vol_col: rv20d              # pakai kolom volatilitas harian (dari tabel prices)
  vol_mode: sqrt              # sqrt = sigma*sqrt(N), (opsi lain: linear = sigma*N)
  prefer_sl_on_tie: true      # bila di hari yang sama high & low tembus, default konservatif  SL
